version: "3.3"
services:
  mariadb:
    image: mariadb:10.3
    env_file:
      - .env
    ports:
      - "3306:3306"

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3307:3306"